### ISSUE TITLE
CameraRig.UnityXR prefab has missing scripts

### ISSUE THREAD

**Issue by FireDragonGameStudio** [ExtendRealityLtd/Tilia.CameraRigs.UnityXR#31]
### Environment

* Code source: Tilia.CameraRigs.UnityXR package 1.1.6
* Platform version: Unity 2019.4.0f1
* 3rd party dependencies: none

### Steps to reproduce
Add Tilia package Tilia.CameraRigs.UnityXR to project and drag CameraRig.UnityXR into the hierarchy.

### Current behavior
Warnings are popping up, considering missing scripts on HeadAnchor, LeftHandAnchor and RightHandAnchor.

![grafik](https://user-images.githubusercontent.com/23502690/85137281-392b9f80-b241-11ea-969f-a2857d5afcb4.png)
![grafik](https://user-images.githubusercontent.com/23502690/85137338-52345080-b241-11ea-9b0c-1d957b942075.png)
![grafik](https://user-images.githubusercontent.com/23502690/85137362-5e201280-b241-11ea-8cdd-b1fdbc3bd1e5.png)

Best regards :)

**Comment by thestonefox** [comment]
You've not followed the steps in the installation instructions:

https://github.com/ExtendRealityLtd/Tilia.CameraRigs.UnityXR/blob/master/Documentation/HowToGuides/Installation/README.md#step-2-configuring-the-unity-project
